### ISSUE TITLE
Laravel 5.4 compatibility

### ISSUE THREAD

**Issue by legreco** [spinen/laravel-browser-filter#10]
Hello, when will this package support laravel 5.4?

**Comment by jimmypuckett** [comment]
Thanks for poking us.  I am updating it right now...

**Comment by jimmypuckett** [comment]
@legreco I have pushed up a feature that is building & assigned it to one of the team members.  Once @ssfinney reviews it, then he will merge it & we will tag a version for release.  Int the mean time, you can use the feature branch if you would like.

**Comment by jimmypuckett** [comment]
We have pushed a new tag for 0.6.0, which should be what you need.  Thanks again.

**Comment by legreco** [comment]
Great! I will test it in my application. Thanks.

**Comment by legreco** [comment]
Hello, its me again I create a fresh application and i tried to block all browsers (just to test it)
But i can always access /home on any browser.
My browserfilter.php file
`
return [

    /*
    |--------------------------------------------------------------------------
    | Filter type
    |--------------------------------------------------------------------------
    |
    | The filter is to apply blocking ("block") or allowing ("allow") strategy
    | using the rules defined below.
    |
    */
    'type'    => 'block',

    /*
    |--------------------------------------------------------------------------
    | Blocked devices, browsers and/or versions
    |--------------------------------------------------------------------------
    |
    | This array defines the items to be filtered out when a request is made
    | to all routes.  There is a three level structure to the array where it
    | goes device -> browser -> version.  The device string can be "Mobile",
    | "Other", or "Tablet" as defined by UAParser\Parser. You can define an
    | array of specific browser names that you are targeting or use "*" to
    | block all browsers of that device type.  At the final level, you can
    | define an array of comparison operators to use for that specific browser
    | or you can use a "*" to block all versions of that browser.  We are
    | using php's version_compare function...
    |
    |      @link http://php.net/manual/en/function.version-compare.php
    |
    | so you can see the operations documented there.
    |
    | Here is an example...
    |
    | 'rules' => [
    |     'Mobile' => '*',
    |     'Other'  => [
    |         'IE'    => '*',
    |     ],
    |     'Tablet' => [
    |         'Opera' => [
    |             '<' => '6',
    |         ]
    |     ],
    | ],
    |
    | In this example, we are allowing/blocking the following...
    |
    |     * All mobile devices
    |     * All versions of IE that is not on a tablet
    |     * Any version of Opera less than 6 on a tablet
    |
    */
    'rules'   => [
        'Mobile' => '*',
        'Other'  => '*',
        'Tablet' => '*'
    ],

    /*
    |--------------------------------------------------------------------------
    | Blocked devices, browsers and/or versions
    |--------------------------------------------------------------------------
    |
    | The name of the route to redirect the user to if the browser is blocked
    |
    */
    'route'   => 'browser_incompatible',

    /*
    |--------------------------------------------------------------------------
    | Duration to cache the browser as being blocked
    |--------------------------------------------------------------------------
    |
    | The time in minutes to cache that the client is blocked
    |
    */
    'timeout' => 3600,

];`
My web.php file

`
Route::get('incompatible_browser',function (){
    return view('errors.incompatible_browser');
})->name('browser_incompatible');


Route::get('/home',  function () {
        return "This is home and but you can't see it";
    }
);`
My Kernel.php file
`class Kernel extends HttpKernel
{
    /**
     * The application's global HTTP middleware stack.
     *
     * These middleware are run during every request to your application.
     *
     * @var array
     */
    protected $middleware = [
        \Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode::class,
        \Illuminate\Foundation\Http\Middleware\ValidatePostSize::class,
        \App\Http\Middleware\TrimStrings::class,
        \Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull::class,
    ];

    /**
     * The application's route middleware groups.
     *
     * @var array
     */
    protected $middlewareGroups = [
        'web' => [
            \App\Http\Middleware\EncryptCookies::class,
            \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
            \Illuminate\Session\Middleware\StartSession::class,
            // \Illuminate\Session\Middleware\AuthenticateSession::class,
            \Illuminate\View\Middleware\ShareErrorsFromSession::class,
            \App\Http\Middleware\VerifyCsrfToken::class,
            \Illuminate\Routing\Middleware\SubstituteBindings::class,
            \Spinen\BrowserFilter\Stack\Filter::class,
        ],

        'api' => [
            'throttle:60,1',
            'bindings',
        ],
    ];

    /**
     * The application's route middleware.
     *
     * These middleware may be assigned to groups or used individually.
     *
     * @var array
     */
    protected $routeMiddleware = [
        'auth' => \Illuminate\Auth\Middleware\Authenticate::class,
        'auth.basic' => \Illuminate\Auth\Middleware\AuthenticateWithBasicAuth::class,
        'bindings' => \Illuminate\Routing\Middleware\SubstituteBindings::class,
        'can' => \Illuminate\Auth\Middleware\Authorize::class,
        'guest' => \App\Http\Middleware\RedirectIfAuthenticated::class,
        'throttle' => \Illuminate\Routing\Middleware\ThrottleRequests::class,
        'browser.allow' => \Spinen\BrowserFilter\Route\AllowFilter::class,
        'browser.block' => \Spinen\BrowserFilter\Route\BlockFilter::class,
    ];
}
`

**Comment by jimmypuckett** [comment]
@legreco Thanks for the report.  I have been able to recreate your report.  I have then done it with a fresh 5.3 app & it works.  I am sorry that I did not do a deep enough test.  That is what I get for only using the built in test.  There is something unique about 5.4's use of filters, so I am going to need to dig a little deeper.

**Comment by legreco** [comment]
Yes, I tried it in fresh laravel 5.2 and 5.3 app. It works in both cases. But it doesn't work in Laravel 5.4 app.

**Comment by jimmypuckett** [comment]
@legreco Just wanted to let you know that we are working through this.  It is a very busy time, at the office, so we are not getting much time to focus on it without interruptions.  I hope to find the cause tonight.

**Comment by legreco** [comment]
yep. :)

**Comment by jimmypuckett** [comment]
@legreco We got it figured out!  (I think...)

It appears that when the `vendor publish` is ran in 5.4, it is not publishing the config file, so the first run defaults to the config in the package, which does not block anything & caches that for 3,600 minutes.  Then (guess here) you copied in the `broserfilter.php` file into `/config` to make the test config.  At that point, the cache is triggered before the new rules, so nothing gets blocked.  Can you test this for us using the 5.4 install that does not work...

1. clear the cache `php artisan cache:clear`
2. make the `broserfilter.php` block all browsers
3. try hitting your route

Our theory is that it will block the request & cache the block.

We are going to look into my the config is not getting published in 5.4, but it is in the other versions.

Thanks for working with us on this.

**Comment by legreco** [comment]
It is true. It was the cache. when i reopened the projet that i freshly created for testing the package i was surprised that everything worked. So i changed the browserfilter.php filter type to allow without clearing the cache to verify your theory, and all browsers where still blocked.
Then I cleared the cache and everything worked as expected.
Thank you a lot for your help!!!

**Comment by jimmypuckett** [comment]
@legreco Glad that was the issue.  We are going to make a few tweaks ( #12 & #13 ) to the package based on this issue that you had.

Please let us know if you run into anything else.

Thanks.
