### ISSUE TITLE
Devices are no longer grouped

### ISSUE THREAD

**Issue by ssfinney** [spinen/laravel-browser-filter#17]
The [UAP-PHP](https://github.com/ua-parser/uap-php) package returns non-grouped values for `$client->device->family`.

For example, Safari works as expected: `Other`

But, iPhones don't: `iPhone` instead of `Mobile`

**Comment by isaac-manubag** [comment]
im experiencing this issue too. I can put 'iPad' and 'iPhone' on browserfilter.php and it will work for those devices but on the android devices it will always get blocked.

**Comment by fhferreira** [comment]
+1 How you do the allow/blocking of Android devices?

**Comment by ssfinney** [comment]
To do this, we need to look at the value coming out of `$client->os->family` to get "Android". I haven't tested this yet, so maybe someone else can try it out real quick. If I can get to this, I will!

Thanks!

**Comment by jimmypuckett** [comment]
@ssfinney I am closing this as it is so old.  Please reopen if someone needs it.
