### ISSUE TITLE
Laravel 5.7 support

### ISSUE THREAD

**Issue by scottgrobinson** [spinen/laravel-browser-filter#21]
Hi,

Could you add 5.7 support please? Not able to upgrade at present.

Thank you :)

**Comment by jimmypuckett** [comment]
@scottgrobinson We are building new version right now.  We will let you know as soon as it is finished.

#22

**Comment by ssfinney** [comment]
@scottgrobinson Done as of v.1.1.0

**Comment by scottgrobinson** [comment]
@ssfinney Thanks - I pulled a few weeks back and realised it was working. Much appreciated.
