### ISSUE TITLE
Middleware not working

### ISSUE THREAD

**Issue by luni23** [spinen/laravel-browser-filter#23]
Hi! I'm using this middleware with my Laravel 5.5 app, following all the steps to make it work and configuring my browserfilter.php file as: 

return [

    'type'    => 'block',

    'rules'   => [
        'Mobile' => [],
        'Other'  => [
            'IE'    => '*',
        ],
        'Tablet' => [],
    ],
    'route'   => 'incompatible_browser',

    'timeout' => 3600,

];

trying to block any access from IE browsers. The route 'incompatible_browser' has a function returning a string, just as the example. But when I try to access my app from IE, the filter doesn't work. 
If anyone can help me i really appreciate it.

**Comment by jimmypuckett** [comment]
@luni23 I am sorry for the delay in responding.  Somehow, we missed the request.  Anyhow, did you get the issue figured out?

**Comment by jimmypuckett** [comment]
I am going to close it as it is so old, but pease reopen it if you are still having an issue.
