### ISSUE TITLE
Browser functionality issues - Laravel Framework 5.5.20

### ISSUE THREAD

**Issue by Chefis** [spinen/laravel-browser-filter#24]
I have been presenting some different issues with different submit buttons

Case 1. Does not work in Chrome Version 71.0.3578.98 (Build official) (64 bits) or in IE 11.472.171340 but works perfectly in Firefox 64.0
Case 2. Does not work in Chrome Version 71.0.3578.98 (Build official) (64 bits) but works perfectly in IE 11.472.171340 and Firefox 64.0
Case 3. Does not work in  IE 11.472.171340 but works perfectly in and Firefox 64.0 and Chrome Version 71.0.3578.98 (Build official) (64 bits) 

In some cases if a open the FF and use the button this will work after on Chrome but if I do this the other way around and try first on Chrome, the button will not work on FF

**Comment by jimmypuckett** [comment]
I am really not following what you are trying to do.  Can you explain how you are using the package?  Maybe add some parts of the code?
