### ISSUE TITLE
"Chromium edge" falls under 'Edge'

### ISSUE THREAD

**Issue by scottgrobinson** [spinen/laravel-browser-filter#32]
Is there a way to "allow" chromium edge, but filter/disallow old school "edge"?

I have the following filter which works for IE & Edge
``` 
   'rules'   => [
        'Mobile' => [],
        'Other'  => [
            'IE'    => '*',
            'Edge'  => '*',

        ],
        'Tablet' => [],
    ],
```

But chromium edge is still blocked. Confusingly, the user agent is showing as 'Edg' rather than 'Edge' so it *should* be let through?

**Chromium Edge**
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4121.0 Safari/537.36 Edg/84.0.495.2

**Old School Edge**
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36 Edge/18.18362

**Comment by ssfinney** [comment]
@scottgrobinson Did you find a solution?

**Comment by scottgrobinson** [comment]
@ssfinney Sort of but not using this package. I decided just to roll my own middleware using Jenssegers\Agent as my needs were simple.

```
<?php

namespace App\Http\Middleware;

use Closure;
use Jenssegers\Agent\Agent;

class BrowserFilter
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
		$agent = new Agent();
		
		$restricted_browsers = ['IE', 'Edge'];
		
		if(in_array($agent->browser(), $restricted_browsers) && $request->route()->getName() != 'incompatible_browser'){
			return redirect('incompatible_browser');
		} else {
	        return $next($request);		
		}
    }
}
```
